# Settings
set -g status-right-length 100
set -g status-interval 2
set -g base-index 1
setw -g pane-base-index 1

set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u

set -g choose-tree-preview on

# Plugins
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-continuum'
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-sidebar'

set -g status-left '#[bg=blue,fg=white] #S #[bg=blue,fg=green]#[default]'
set -g status-right '#{?client_prefix,#[bg=green,fg=blue]#[bg=blue,fg=white] Wait ,#{?pane_in_mode,#[bg=green,fg=yellow]#[bg=yellow,fg=white] Copy ,#{?synchronize-panes,#[bg=green,fg=red]#[bg=red,fg=white] Sync ,#[bg=green,fg=white]}}}#[bg=white,fg=black] %d.%m.%Y #[bg=white,fg=yellow]#[bg=yellow,fg=black] %H:%M #[default]'

set -g window-status-format '#[bg=green,fg=black] ❬#I❭ #W'
set -g window-status-current-format '#[bg=green,fg=white,bold] ❰#I❱ #W'

# Initialize PPM (keep this line at the very bottom of .psmux.conf)keep this line at the very bottom of tmux.conf)
run '~/.psmux/plugins/ppm/ppm.ps1'
