# Settings
set -g status-left-length 100
set -g status-right-length 100
set -g status-interval 5
set -g base-index 1
setw -g pane-base-index 1

set -g mouse on

set -g choose-tree-preview on

# Variables
set -g @var_status_date_format '%d.%m.%Y'
set -g @var_status_time_format '%H:%M'

set -g @var_status_prefix_prefix 'Wait'
set -g @var_status_prefix_copy 'Copy'
set -g @var_status_prefix_sync 'Sync'

# Plugins
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-continuum'
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @plugin 'psmux-plugins/psmux-sensible'

# Status
set -g @var_brightgray 'color247'
set -g @var_darkgray 'color235'
set -g @var_gray 'color241'

set -g @var_status_prefix '#{?client_prefix,#[bg=#{@var_darkgray},fg=blue]#[bg=blue,fg=white] #{@var_status_prefix_prefix} #[bg=blue,fg=#{@var_gray}],#{?pane_in_mode,#[bg=#{@var_darkgray},fg=yellow]#[bg=yellow,fg=black] #{@var_status_prefix_copy} #[bg=yellow,fg=#{@var_gray}],#{?pane_synchronized,#[bg=#{@var_darkgray},fg=red]#[bg=red,fg=white] #{@var_status_prefix_sync} #[bg=red,fg=#{@var_gray}],#[bg=#{@var_darkgray},fg=#{@var_gray}]}}}'
set -g @var_status_right_style 'bg=#{@var_gray},fg=white'

set -g status-style 'bg=#{@var_darkgray},fg=white'
set -g status-left '#[bg=brightblue,fg=white]  #S #[bg=#{@var_darkgray},fg=brightblue]#[default]'
set -g status-right '#{E:@var_status_prefix}#[#{E:@var_status_right_style}]  #{E:@var_status_date_format} #[bg=#{@var_gray},fg=#{@var_darkgray}]#[#{E:@var_status_right_style}]  #{E:@var_status_time_format} #[default]'

set -g window-status-separator ''
set -g window-status-format '#[bg=#{@var_gray},fg=#{@var_darkgray}]#[bg=#{@var_gray},fg=white] #I #[bg=#{@var_gray},fg=#{@var_darkgray}]#[bg=#{@var_gray},fg=white] #W #[bg=#{@var_darkgray},fg=#{@var_gray}]'
set -g window-status-current-format '#[bg=#{@var_brightgray},fg=#{@var_darkgray}]#[bg=#{@var_brightgray},fg=black] #I #[bg=#{@var_brightgray},fg=#{@var_darkgray}]#[bg=#{@var_brightgray},fg=black] #W #[bg=#{@var_darkgray},fg=#{@var_brightgray}]'

# Initialize PPM (keep this line at the very bottom of .psmux.conf)keep this line at the very bottom of tmux.conf)
run '~/.psmux/plugins/ppm/ppm.ps1'
