# Settings
set -g status-interval 2
set -g status-right-length 100
set -g base-index 1
setw -g pane-base-index 1

# Plugins
set -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'laktak/tome'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'spywhere/tmux-named-snapshot'
set -g @plugin 'thewtex/tmux-mem-cpu-load'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cowboy'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tpm'

set -g status-left '#[bg=blue,fg=white] #S #[bg=blue,fg=green]#[default]'
set -g status-right "#{prefix_highlight} #[fg=green] #($TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load -q -i 2 -v -a 0) #[bg=white,fg=black] %d.%m.%Y #[bg=white,fg=yellow]#[bg=yellow,fg=black] %H:%M #[default]"

set -g window-status-format "#[bg=green,fg=black] ❬#I❭ #W"
set -g window-status-current-format "#[bg=green,fg=white,bold] ❰#I❱ #W"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
